[build]
builder = "DOCKERFILE"
buildCommand = ""

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
RAILS_ENV = "production"
RACK_ENV = "production" 