[build]
builder = "nixpacks"
buildCommand = "bundle install && rails assets:precompile"

[deploy]
startCommand = "bundle exec rails server -b 0.0.0.0 -p $PORT"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
RAILS_ENV = "production"
RACK_ENV = "production" 