services:
  - type: web
    name: istanbul-merkez-tesisat
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: istanbul_merkez_tesisat_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: istanbul_merkez_tesisat_db
    databaseName: istanbul_merkez_tesisat
    user: istanbul_merkez_tesisat 