# Configuration Kamal pour le déploiement
service: service-web
image: ayvemake/service-web
registry:
  username: ayvemake
  password: <%= ENV["DOCKER_TOKEN"] %>

servers:
  web:
    hosts:
      - votre_ip_serveur
    labels:
      traefik.enable: true

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

volumes:
  - "service_web_storage:/rails/storage"
  - "service_web_uploads:/rails/public/uploads"

builder:
  args:
    RUBY_VERSION: "3.2.2"

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  logs: app logs -f
  dbconsole: app exec --interactive --reuse "bin/rails dbconsole"
