development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || ('x' * 32) %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || ('x' * 32) %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
